version: "3"
services:
  tcp:
    build: ./tcp-server
    ports:
    - "8888:8888"
    volumes:
    - ./tcp-server:/tcp-server
    depends_on:
    - http
  http:
    build: ./http-server
    ports:
    - "9000:9000"
