version: "3"
services:
  server:
    build: ./server
    ports:
    - "80:80"
    volumes:
    - ./server:/server
    depends_on:
    - web-app
  web-app:
    build: ./web-app
    ports:
    - "9000:9000"
